MDBoxLayout:
    orientation: 'vertical'
    #Top of application bar two clickable items
    MDTopAppBar:
        background_color: (252/255.0, 157/255.0, 249/255.0)
        title: "BuddyAI"
        left_action_items:[["menu"]]
        right_action_items: [["image\logohead.png"]]
    #bottom nav used to navigate through pages
    MDBottomNavigation:
    #1st item
        MDBottomNavigationItem:
            name: 'Home Screen'
            text:"Home"
            icon: 'image\home.png'
            Image:
                source: 'test2.jpg'
                allow_stretch: True
                size_hint: None, None
                size: root.size
            FloatLayout:
                MDLabel:
                    text:"Home Screen"
                    font_size: 20
                    pos_hint: {"x":0.1, "top":0.7}
                    size_hint: 0.35, 0.15

    #2nd item
        MDBottomNavigationItem:
            name: 'Chatbot Screen'
            text: "Buddy AI"
            icon: 'image\logog.png'
            
            Image:
                source: 'test2.jpg'
                allow_stretch: True
                size_hint: None, None
                size: root.size
                
            FloatLayout:
                MDLabel:
                    text:"Chatbot Screen"
                    font_size: 20
                    pos_hint: {"x":0.1, "top":0.7}
                    size_hint: 0.35, 0.15
        
        #3rd item
        MDBottomNavigationItem:
            name: 'Settings'
            text: "Settings"
            icon: 'image\gear.png'
            Image:
                source: 'test2.jpg'
                allow_stretch: True
                size_hint: None, None
                size: root.size
            FloatLayout:
                MDLabel:
                    text:"Settings Screen"
                    font_size: 20
                    pos_hint: {"x":0.1, "top":0.7}
                    size_hint: 0.35, 0.15

        
